services:
  db:
    image: postgres:16-alpine
    container_name: police-postgres
    environment:
      POSTGRES_DB: police_db
      POSTGRES_USER: police_user
      POSTGRES_PASSWORD: police_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U police_user -d police_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: